"""Alembic environment. Reads BIBLE_IU_DATABASE_URL so the same env
var the app uses also drives migrations.

Schema source of truth: `backend.data.models:Base.metadata`. New
revisions can be autogenerated with:

    alembic revision --autogenerate -m "describe the change"

then reviewed by hand before commit (autogen misses constraint
renames and indexes added via __table_args__).
"""
from __future__ import annotations

import os
from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

# Pull the model metadata so --autogenerate sees the live schema.
from backend.data.models import Base

config = context.config
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata

# Resolve the DB URL at runtime — Fly secrets / .env / CI env all
# work without editing alembic.ini.
db_url = os.environ.get("BIBLE_IU_DATABASE_URL") or "sqlite:///backend/data/bible-iu.sqlite"
config.set_main_option("sqlalchemy.url", db_url)


def run_migrations_offline() -> None:
    """Emit SQL without a live DB connection (useful for review)."""
    context.configure(
        url=db_url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        render_as_batch=db_url.startswith("sqlite"),
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = engine_from_config(
        config.get_section(config.config_ini_section) or {},
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        # `render_as_batch=True` makes SQLite-friendly ALTER TABLE
        # emit via a copy-and-rename pattern, which is the only way
        # to add/drop columns in SQLite without losing data.
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            render_as_batch=db_url.startswith("sqlite"),
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
